101: "Applicant did not meet all immigration requirements"
102: "Applicant did not receive foster care in this state"
103: "Applicant did not receive Medicaid while receiving foster care"
104: "Applicant does not have 40 work quarters"
106: "Applicant does not meet all of the Medicaid eligibility criteria"
107: "Applicant does not meet criteria for CHIP eligibility"
108: "Applicant does not meet requirements for a non-MAGI referral"
109: "Applicant does not meet the eligibility criteria for emergency Medicaid"
111: "Applicant has exceeded the 7 year limit of Medicaid coverage for his/her immigration status"
112: "Applicant has exceeded the 8 month limit for Refugee Medical Assistance"
114: "Applicant has other insurance"
115: "Applicant is 19 years of age or older and the state does not cover young adults under age 20 or 21"
117: "Applicant is entitled to or enrolled in Medicare"
118: "Applicant is not a child"
119: "Applicant is not a child or pregnant woman"
120: "Applicant is not a pregnant woman"
122: "Applicant is pregnant"
123: "Applicant is not between the ages of 19 and 64 (inclusive)"
124: "Applicant not pregnant or within postpartum period"
125: "Applicant was not in foster care when he/she aged out"
126: "Applicant's age is greater than or equal to 26"
127: "Applicant's age is not within the allowed age range"
128: "Applicant's dependent child does not have minimal essential coverage"
129: "Both parents are employed"
130: "Caretaker does not meet any adult definition for child"
131: "Caretaker does not meet any relative definition for child"
132: "Caretaker does not meet standard definition for child"
137: "Child is 18 years old but not a student"
138: "Medicaid household income exceeds the FPL threshold to be covered by CHIP if the applicant has access to state employee health coverage"
139: "CHIP waiting period is still in effect"
143: "Five Year bar in effect"
146: "No child met all criteria for parent caretaker category"
147: "No child of required age living with the parent or caretaker relative"
151: "The mother is eligible for Medicaid"
155: "State does not provide CHIP to applicants with access to state health insurance"
309: "Applicant does not meet residency requirement"
338: "Applicant did not meet all the criteria for income override rule"
339: "Applicant Title II work quarters did not meet the criteria"
340: "Income is greater than 100% FPL"
373: "Income exceeds the FPL level for Refugee Medical Assistance"
380: "Applicant is ineligible for CHIP due to Medicaid eligibility as a former foster care child"
389: "Caretaker does not meet the definition of domestic partner"
394: "Applicant is over the age limit for the young adult threshold in the state"
400: "Applicant was not formerly in foster care"
401: "Applicant did not meet the requirements for any eligibility category"
402: "Applicant's income is greater than the threshold for all eligible categories"
403: "Applicant is a full-time student claimed as a dependent by someone in another state"
404: "Applicant lives out of state"
405: "Applicant is incarcerated"
406: "Applicant is eligible for Medicaid"
407: "Applicant is eligible for Refugee Medical Assistance"
408: "Applicant's income is too high for Unborn Child category"
409: "Applicant is not lawfully present in the United States"
410: "Applicant is not a victim of trafficking"
